### ISSUE TITLE
Missing script issue

### ISSUE THREAD

**Issue by nehasachdeva0708** [planetoftheweb/angularregistration#9]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\Git\\usr\\local\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@4.6.1
3 info using node@v8.1.2
4 verbose stack Error: missing script: start
4 verbose stack     at run (C:\Program Files\Git\usr\local\node_modules\npm\lib\run-script.js:151:19)
4 verbose stack     at C:\Program Files\Git\usr\local\node_modules\npm\lib\run-script.js:61:5
4 verbose stack     at C:\Program Files\Git\usr\local\node_modules\npm\node_modules\read-package-json\read-json.js:356:5
4 verbose stack     at checkBinReferences_ (C:\Program Files\Git\usr\local\node_modules\npm\node_modules\read-package-json\read-json.js:320:45)
4 verbose stack     at final (C:\Program Files\Git\usr\local\node_modules\npm\node_modules\read-package-json\read-json.js:354:3)
4 verbose stack     at then (C:\Program Files\Git\usr\local\node_modules\npm\node_modules\read-package-json\read-json.js:124:5)
4 verbose stack     at C:\Program Files\Git\usr\local\node_modules\npm\node_modules\read-package-json\read-json.js:311:12
4 verbose stack     at C:\Program Files\Git\usr\local\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:512:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:500:12)
5 verbose cwd c:\WebApps\angularregistration
6 verbose Windows_NT 10.0.17134
7 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\Git\\usr\\local\\node_modules\\npm\\bin\\npm-cli.js" "start"
8 verbose node v8.1.2
9 verbose npm  v4.6.1
10 error missing script: start
11 verbose exit [ 1, true ]

**Comment by richwertz** [comment]
Hi Ray,
`> grunt` didn't work in git bash to start the live preview server. I used `> gulp` and it worked with that. Additionally, for users having difficulties starting the dev browser, who might encounter an error message like '`bash: grunt: command not found`' or '`bash: gulp: command not found`,' they can try putting the following code at line 3 in package.json:  ```
 "scripts": {
    "start": "gulp"
  },
```
and then run `> npm start` in git bash.
Thanks,
Rich Wertz
